// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PTPMBTL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221214062539_QuanLiChuyenBayCreate")]
    partial class QuanLiChuyenBayCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PTPMQL.Models.Account", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("PTPMQL.Models.CheckAccount", b =>
                {
                    b.Property<string>("CheckUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CheckUserName");

                    b.ToTable("CheckAccounts");
                });

            modelBuilder.Entity("PTPMQL.Models.KhachHang", b =>
                {
                    b.Property<string>("IDKhachHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoBan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("PTPMQL.Models.Meeting", b =>
                {
                    b.Property<string>("IDNhanVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChuDeHop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaChuyenBay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDungHop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDNhanVien");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("PTPMQL.Models.Passenger", b =>
                {
                    b.Property<string>("HoChieu")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HovaTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HoChieu");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("PTPMQL.Models.QuanLiChuyenBay", b =>
                {
                    b.Property<string>("MaChuyenBay")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiemKhoiHanh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHanhKhach")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThoiGianXuatPhat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaChuyenBay");

                    b.ToTable("QuanLiChuyenBays");
                });

            modelBuilder.Entity("PTPMQL.Models.QuanLiHangGui", b =>
                {
                    b.Property<string>("MaHangGui")
                        .HasColumnType("TEXT");

                    b.Property<string>("NgayGioGuiHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrongLuongHangGui")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("XacNhanHopLe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaHangGui");

                    b.ToTable("QuanLiHangGuis");
                });
#pragma warning restore 612, 618
        }
    }
}
